linters:
  enable:
    - bodyclose
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused
    - revive

linters-settings:
  gocyclo:
    # Min code complexity to report, 30 by default (recommended 10-20)
    min-complexity: 25
  lll:
    line-length: 150
