# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy

dockers:
- dockerfile: Dockerfile
  image_templates:
    - ghcr.io/u21-public/terraform-plan-analyzer:{{ .Version }}
    - ghcr.io/u21-public/terraform-plan-analyzer:latest
  build_flag_templates:
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.title={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--platform=linux/amd64"
    - "--target=goreleaser"
    - "--pull"
  goos: linux
  goarch: amd64
  goamd64: v1
  use: buildx
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}}'
    goos:
#      - freebsd
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'terraform-plan-analyzer'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256
release:
# If you want to manually examine the release before its live, uncomment this line:
 draft: false
changelog:
  skip: false
  use: github