repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: 'Run linting'
        alias: golangci-lint
        files: '^[cmd/|internal/]'
        types: [go]
        language: system
        entry: bash -c 'make lint'
  - repo: local
    hooks:
      - id: goimports
        name: 'Run goimports'
        alias: goimports
        files: '^[cmd/|internal/]'
        exclude: "pb.go"
        types: [go]
        language: system
        entry: goimports -w -local github.com/u21-public/terraform-plan-analyzer
