name: Analyze Plans
description: Unstashes plans and runs report on them
inputs:
  plan_archive_id:
    type: string
    default: tfplan
  gh_token:
    type: string
    required: true
  version:
    type: string
    required: false
    default: "0.5.0"
runs:
  using: composite
  steps:
    - name: Download Plans
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.plan_archive_id }}
        path: tfplans
    - name: get PR info
      id: get-pr-number
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run and Post Report
      id: run-report
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        GITHUB_OWNER: ${{ github.repository_owner	}}
        GITHUB_REPOSITORY: ${{ github.event.repository.name }}
        GITHUB_PR_NUMBER: ${{ steps.get-pr-number.outputs.pr_number }}
        VERSION: ${{ inputs.version }}
      run: |
        docker run \
          -v "$(pwd)/tfplans/:/tfplans" \
          -e GITHUB_TOKEN -e GITHUB_REPOSITORY -e GITHUB_OWNER -e GITHUB_PR_NUMBER \
          ghcr.io/u21-public/terraform-plan-analyzer:${{ env.VERSION }} \
          --tfplans /tfplans --github