name: pull request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
        version: "2022.1.1"
      - name: Fmt and Vet
        shell: bash
        run: |
          go vet ./...
          test -z $(gofmt -l .)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Test
        shell: bash
        run: |
          go test -v -cover -shuffle on ./...