name: pull request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Test
        shell: bash
        run: |
          sh scripts/lint.sh
  test:
    on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Test
        shell: bash
        run: |
          go test -v -cover -shuffle on ./...